### ISSUE TITLE
file is too big

### ISSUE THREAD

**Issue by mohamadbij** [Fomchenkov/converter-voice-telegram-bot#3]
File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: file is too big
"
2024-03-12 19:01:36,660 (__init__.py:1083 MainThread) ERROR - TeleBot: "Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: file is too big"
2024-03-12 19:01:38,020 (__init__.py:1085 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\telebot\__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\telebot\util.py", line 156, in raise_exceptions
    raise self.exception_info
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\telebot\util.py", line 100, in run
    task(*args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\telebot\__init__.py", line 6395, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "C:\converter\main.py", line 16, in audio_handler
    file_info = bot.get_file(message.audio.file_id)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\telebot\__init__.py", line 1255, in get_file
    return types.File.de_json(apihelper.get_file(self.token, file_id))
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\telebot\apihelper.py", line 211, in get_file
    return _make_request(token, method_url, params={'file_id': file_id})
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: file is too big
"

**Comment by mallkorebit** [comment]
The telegram bot can only accept files up to 50 MB
